// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBClzyiSJAo7VoJJDBDq5_0824T9536yXs',
    appId: '1:772915166272:web:63eb0ba5d15b742db533a5',
    messagingSenderId: '772915166272',
    projectId: 'bit-notes-app',
    authDomain: 'bit-notes-app.firebaseapp.com',
    storageBucket: 'bit-notes-app.appspot.com',
    measurementId: 'G-KRMY30DSGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv22UhuJIeCZnwONQJBaXpaOyARqOIL3A',
    appId: '1:772915166272:android:56c01ac21a4c6e2cb533a5',
    messagingSenderId: '772915166272',
    projectId: 'bit-notes-app',
    storageBucket: 'bit-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDW5-bVJiHY24Twz4zVBEKQDuRCVAIsR3U',
    appId: '1:772915166272:ios:c09e6c08c1197b8db533a5',
    messagingSenderId: '772915166272',
    projectId: 'bit-notes-app',
    storageBucket: 'bit-notes-app.appspot.com',
    iosClientId: '772915166272-eaqkurocmvqbe0omg1ta57iimbt6v169.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDW5-bVJiHY24Twz4zVBEKQDuRCVAIsR3U',
    appId: '1:772915166272:ios:c09e6c08c1197b8db533a5',
    messagingSenderId: '772915166272',
    projectId: 'bit-notes-app',
    storageBucket: 'bit-notes-app.appspot.com',
    iosClientId: '772915166272-eaqkurocmvqbe0omg1ta57iimbt6v169.apps.googleusercontent.com',
    iosBundleId: 'com.example.bitApp',
  );
}
